sudo: required

services:
 - docker

language: bash

env:
  matrix:
  - DOCKER_ARCH=amd64
  - DOCKER_ARCH=arm64
  - DOCKER_ARCH=arm

before_install:
 - chmod +x build/build.sh

script:
- ./build/travis_build.sh

jobs:
  include:

  - stage: Manifest
    script:
    - ./build/travis_manifest.sh
    env:
